name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/adstex
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: pypa/gh-action-pypi-publish@release/v1
